id: P003155
initial_creation_type: ocr
source_metadata:
  id: bdr:W19230
  title: དོ་ཧ་སྐོར
  author: ''
  volumes:
    b0ea1ffc53f3403fb98f9672f3fc48f0:
      image_group_id: I1656
      title: ''
      volume_number: 1
      total_pages: 307
