id: P003155
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:43:59.198364
source_metadata:
  id: bdr:W19230
  title: དོ་ཧ་སྐོར
  author: ''
  volumes:
    b0ea1ffc53f3403fb98f9672f3fc48f0:
      image_group_id: I1656
      title: ''
      volume_number: 1
      total_pages: 307
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
