id: I05AE989F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:58:22+00:00'
last_modified: '2022-06-07T17:57:48.893195+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19230
  title: དོ་ཧ་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EBBA:
      image_group_id: I1656
      title: ''
      total_pages: 307
      order: 1
      base_file: EBBA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
